version: '3.8'

networks:
  movies-network:

services:

  zipkin:
    image: openzipkin/zipkin
    restart: always
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - movies-network

  discovery-server:
    image: heslav/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - '8761:8761'
    networks:
      - movies-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin

  api-gateway:
    image: heslav/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - '8888:8888'
    networks:
      - movies-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - discovery-server
      - zipkin

  movie-service:
    image: heslav/movie-service:latest
    container_name: movie-service
    pull_policy: always
    ports:
      - '8000:8000'
    networks:
      - movies-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - discovery-server
      - zipkin
      - api-gateway

  imdb-service:
    image: heslav/imdb-service:latest
    container_name: imdb-service
    pull_policy: always
    ports:
      - '8100:8100'
    networks:
      - movies-network
    environment:
      - IMDB_API_KEY=YOUR API KEY
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - discovery-server
      - zipkin
      - api-gateway

  recommendation-service:
    image: heslav/recommendation-service:latest
    container_name: recommendation-service
    pull_policy: always
    ports:
      - '8200:8200'
    networks:
      - movies-network
    environment:
      - GPT_API_KEY=YOUR API KEY
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - discovery-server
      - zipkin
      - api-gateway
